# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in `train.py` and `eval.py`
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
data_dir: ${paths.root_dir}/datasets

# path to data directory
config_dir: ${paths.root_dir}/configs

# path to logging directory
out_name: outputs
out_dir: ${paths.root_dir}/${paths.out_name}

# path to model directory
model_cache_dir: ${paths.root_dir}/model_cache

# path to model directory
model_dir: ${paths.root_dir}/models

# path to model directory
checkpoints_dir: ${paths.root_dir}/checkpoints

# path to logging directory
log_dir: ${paths.root_dir}/logs

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
hydra_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}
