# To run this setting: python -m iif.job task=5_metrics/v0_emission
defaults:
  - 5_metrics@_here_: default

input:
  pred: 
    modality: roughness

metrics_cfg:
  l2:
    _target_: torchmetrics.MeanSquaredError
  psnr: 
    _target_: iif.component.loss.psnr.PeakSignalNoiseRatio
    data_range: 1.0
  ssim:
    _target_: torchmetrics.image.StructuralSimilarityIndexMeasure
    data_range: 1.0
  lpips:
    _target_: torchmetrics.image.LearnedPerceptualImagePatchSimilarity
    net_type: vgg
    normalize: True