# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - task: null

  - environment/paths@paths: default
  - environment/extras@extras: default
  - hydra: default

_convert_: object

# tags to help you identify your experiments
# you can overwrite this in experiment configs
tags: []

seed: 0

