# To run this setting: python -m iif.job task=3_inverse_rendering/lighting/v0_2_iris_ldr paths.out_name=outputs/v2
defaults:
  # - /component/logger@logger: console
  - /component/logger@logger: wandb
  - /component/scene@scene: indoor_synthetic/kitchen

_target_: iif.task.train.Train

input:  # Define the high-level inputs to this task
  _target_: iif.utils.config.native_dict
  _recursive_: False
  segmentation_version: v1_gt
  emitter_init_version: v0_iris_init
  crf:
    _target_: iif.utils.model.load_model
    _cfg_: ${paths.out_dir}/${...scene.input.scene_type}/${...scene.output.scene_name}/train/0_baking_slf/v0_iris_init/crf.yaml
    pt: ${paths.out_dir}/${...scene.input.scene_type}/${...scene.output.scene_name}/train/0_baking_slf/v0_iris_init/crf.pt
    freeze: True
  brdf:
    _target_: iif.utils.model.load_model
    cfg: 
      _target_: iif.component.model.brdf.TransformedBRDF
      brdf_base:
        _target_: iif.utils.model.load_model
        _cfg_: ${paths.out_dir}/${.....scene.input.scene_type}/${.....scene.output.scene_name}/train/2_aggregation/v5_cm_soft_fullmat/brdf.yaml
        pt: ${paths.out_dir}/${.....scene.input.scene_type}/${.....scene.output.scene_name}/train/2_aggregation/v5_cm_soft_fullmat/brdf.pt
        freeze: True
      brdf_transform:
        _target_: iif.component.model.brdf.LinearObjBRDFTransform
        semantic_net:
          _target_: iif.utils.model.load_model
          _cfg_: ${paths.out_dir}/${......scene.input.scene_type}/${......scene.output.scene_name}/train/2_aggregation/segmentation/${.....segmentation_version}/segmentation.yaml
          pt: ${paths.out_dir}/${......scene.input.scene_type}/${......scene.output.scene_name}/train/2_aggregation/segmentation/${.....segmentation_version}/segmentation.pt
          freeze: True
    pt: null
    freeze: True
  emitter:
    _target_: iif.utils.model.load_model
    _cfg_: ${paths.out_dir}/${...scene.input.scene_type}/${...scene.output.scene_name}/train/3_get_emitter/${..emitter_init_version}/emitter.yaml
    pt: ${paths.out_dir}/${...scene.input.scene_type}/${...scene.output.scene_name}/train/3_get_emitter/${..emitter_init_version}/emitter.pt
    freeze: False
  postfix: ""

output:  # Define the high-level outputs to this task
  folder_path: ${..scene.output.folder_path}/${hydra:runtime.choices.task}${..input.postfix}

logger:
  name: ${hydra:runtime.choices.task}${..input.postfix}
  tags: 
    - lighting
    - ${...scene.output.scene_name}
    - ${...scene.input.scene_type}

module:
  _target_: iif.component.task.inverse_rendering.inverse_rendering.InverseRenderingModule
  _recursive_: False
  forward_cfg: 
    spp: 128
    spp_batch: 32
    rendering_type: path_tracing  # shading_cache | path_tracing
    depth: 1
    grad_depth:
      brdf: 0
      emitter: 1
  model_cfg:
    scene_path: ${...scene.input.scene_path}
    num_objects: ${...scene.input.num_objects}
    ckpt_path: null # ${paths.out_dir}/2_aggregation/v3_1_2_uncertainty_transformer/indoor_synthetic/kitchen/train/brdf.pt
    crf: ${...input.crf}
    brdf: ${...input.brdf}
    emitter: ${...input.emitter}
  loss_cfg: 
    rgb_type: ldr  # ldr | hdr
    regularizations:
      - brdf
      - emitter
    weight:
      brdf_transform_albedo: 1e-2  # Transformation should be minimal
      brdf_transform_roughness: 5e-4   # Transformation should be minimal
      brdf_transform_metallic: 5e-4   # Transformation should be minimal
      brdf_diffuse: 5e-4   # As diffuse as possible -> roughness=1, metallic=0, original 5e-4
      emitter_monochrome: 0
      emitter_radiance: 0
  optimizer_cfg:
    optimizer: SGD
    learning_rate: 100.
    weight_decay: 0
  scheduler_cfg:
    milestones: 
      - 1
      - 2
    scheduler_rate: 0.2

datamodule:
  _target_: iif.component.datamodule.datamodule.DataModule
  _recursive_: false
  _convert_: object
  sampling_cfg:
    batch_size: 1
    num_workers: 0
    shuffle: True
    sampler:
      _target_: iif.component.datamodule.sampler.subset_repeated.SubsetRepeatedCacheSampler
      indices: null
      shuffle: True
      seed: 0
  dataset_cfg: 
    _target_: ${...scene.dataset_cfg.ray_based_target}
    root: ${...scene.dataset_cfg.root}
    transforms_file: ${...scene.dataset_cfg.transforms_file}
    res_scale: ${...scene.dataset_cfg.res_scale}
    subsampling_factor: ${...scene.dataset_cfg.subsampling_factor} 
    single_view_ref_root: ${paths.out_dir}/${...scene.input.scene_type}/${...scene.output.scene_name}/train/1_single_view_prediction/v2_rgbx
    features_to_include: 
      - rays
      - index
      - rgbs_hdr
      - rgbs_ldr
      - segmentation
      - exposure
    chunk_size: 8192
    transform: ${...scene.dataset_cfg.transform}

trainer:
  _target_: pytorch_lightning.Trainer
  min_epochs: 1
  max_epochs: 1
  # detect_anomaly: True
  check_val_every_n_epoch: False
  accelerator: gpu
  devices: 1
  callbacks: 
    _target_: iif.environment.hydra.arguments.dict_to_list
    d: ${...callback}
  logger: ${..logger}

callback: 
  dataset_reshuffle:
    _target_: iif.component.callback.dataset_reshuffle.DatasetReshuffle
  # emitter_logging:
  #   _target_: iif.component.callback.emitter_pruning.EmitterPruning
  #   model: emitter
  #   pruning_cfg:
  #     absolut_threshold: 0.
  #     relative_threshold: null
  #     percentile_threshold: null
  #   log_schedule:
  #     on_train_batch_end: ::100
  update_importance_sampling:
    _target_: iif.component.callback.model_method_call.ModelMethodCall
    _convert_: object
    callbacks:
      emitter: update_sampling
    log_schedule:
      on_train_batch_end: 1000
  early_emitter_pruning:
    _target_: iif.component.callback.emitter_pruning.EmitterPruning
    model: emitter
    pruning_cfg:
      absolut_threshold: 3.1e-2  # Prune all emitter, which did not receive any grad so far
      relative_threshold: null
      percentile_threshold: null
    log_schedule:
      on_train_batch_end: 100
  emitter_pruning:
    _target_: iif.component.callback.emitter_pruning.EmitterPruning
    model: emitter
    pruning_cfg:
      absolut_threshold: null
      relative_threshold: 5e-2
      percentile_threshold: null
    log_schedule:
      on_train_batch_end: 1000
  anneal_emitter_regularization:
    _target_: iif.component.callback.model_config_change.ModelConfigChange
    _convert_: object
    change_type: set
    model_cfg:
      loss_cfg:
        weight: 
          emitter_radiance: 0.  # 0.1
    log_schedule:
      on_train_batch_end: 1000
  model_summary:
    _target_: pytorch_lightning.callbacks.ModelSummary
    max_depth: 2
  brdf_saving:
    _target_: iif.component.callback.model_saving.ModelSaving
    model_to_save: brdf
    out_path: ${...output.folder_path}/brdf.pt
  crf_saving:
    _target_: iif.component.callback.model_saving.ModelSaving
    model_to_save: crf
    out_path: ${...output.folder_path}/crf.pt
  emitter_saving:
    _target_: iif.component.callback.model_saving.ModelSaving
    model_to_save: emitter
    out_path: ${...output.folder_path}/emitter.pt
  iteration_logger:
    _target_: iif.component.callback.iteration_logger.IterationLogger
    context: iteration
    log_step: True
    log_epoch: True
  learning_rate_change_monitor:
    _target_: iif.component.callback.learning_rate_change_monitor.LearningRateChangeMonitor
    logging_interval: epoch
    log_momentum: false
  loss_logger:
    _target_: iif.component.callback.batch_logger.BatchLogger
    context: loss
    output_keys_to_log: [ "loss*" ]
    batch_keys_to_log: []
    verbose: False
    is_metric: True
    log_schedule:
      on_train_batch_end: ::1
  metric_logger:
    _target_: iif.component.callback.batch_logger.BatchLogger
    context: analytics
    output_keys_to_log: [ "metric*" ]
    batch_keys_to_log: []
    verbose: False
    is_metric: False
    log_schedule:
      on_train_batch_end: ::1
  validation_evaluator:
    _target_: iif.component.callback.validation_logger.ValidationLogger
    context: validation
    forward_cfg: 
      jitter_within_pixel: True
      spp: 32
      spp_batch: 1
      denoising: True
      do_prefilter: False
      do_emissionfilter: False
    sample_ids: ${...scene.vis_cfg.log_indices}
    stage: train
    dataset_kwargs:
      target: ${....scene.dataset_cfg.image_based_target}
      features_to_include: 
      - rays
      - index
      - rgbs_ldr
      - rgbs_hdr
      - segmentation
      - exposure
      - emission 
      - crf
      - albedo
      - roughness
      - metallic
    keys_to_average:
      - output/metrics/*
    keys_to_log: 
      - batch/rgbs_ldr
      - batch/rgbs_hdr
      - output/rgb/*
      - output/brdf/*
      - output/crf/*
      - output/emitter/*
      - output/metrics/*
    log_schedule:
      on_train_batch_end: 0::200